name: Add to project

on:
  issues:
    types: [opened, transferred, reopened]
  pull_request_target:
    types: [opened, reopened]

jobs:
  add-to-project:
    uses: piranesi0/atlas-meta/.github/workflows/add-to-project.yml@main
    with:
      app-id: ${{ vars.ADD_TO_PROJECT_APP_ID }}
    secrets:
      app-private-key: ${{ secrets.ADD_TO_PROJECT_APP_KEY }}

